package com.based.kotlin.utilities.constants

object ConstantsDeeplink {
    const val NAVIGATE_TO_TRANSFER_EDIT_CASH = "transfer-edit-cash"
    const val NAVIGATE_TO_TRANSACTION_CONFIRMATION_CUSTOMER = "transaction-confirmation-customer"
    const val NAVIGATE_TO_TRANSACTION_CONFIRMATION_GB = "transaction-confirmation-gb"
    const val NAVIGATE_TO_TRANSFER_EDIT_SCRIPT = "transfer-edit-script"
    const val NAVIGATE_TO_WAITING_ADVERTISEMENT_SUPERVISOR = "waiting-advertisement-supervisor"
    const val NAVIGATE_TO_TRANSFER_EDIT_DEBET = "transfer-edit-debet"
    const val NAVIGATE_TO_NUMERIC_AUTHORIZATION_VERIFICATION_LANDING = "numeric-authorization-verification-landing"
    const val NAVIGATE_TO_NUMERIC_AUTHORIZATION_LANDING_PIN = "numeric-authorization-landing-pin"
    const val NAVIGATE_TO_ACCOUNT_MAINTENANCE_UPLOAD_DOCUMENT = "account-maintenance-upload-document"
    const val NAVIGATE_TO_CDM_UPLOAD_DOCUMENT = "cdm-upload-document"
    const val NAVIGATE_TO_CUSTOMER_DATA_MAINTENANCE_UPDATE = "customer-data-maintenance-update"
    const val NAVIGATE_TO_SUPERVISOR_CONFIRMATION = "supervisor-confirmation"
    const val NAVIGATE_TO_NUMERIC_OTP_SPV_RTGS = "numeric-authorization-otp-spv-rtgs"
    const val NAVIGATE_TO_TRANSACTION_PREVIEW_SKP_SUPERVISOR = "transaction_preview_skp_supervisor"
    const val NAVIGATE_TO_NUMERIC_OTP_SPV_OVERBOOKING = "numeric-authorization-otp-spv-overbooking"
    const val NAVIGATE_TO_TRANSACTION_PREVIEW_SKP = "transaction_preview_skp"
    const val NAVIGATE_TO_CUSTOMER_WARKAT_VERIFICATION = "transaction_customer_warkat_verification"
    const val NAVIGATE_TO_REFUSAL_WARKAT = "transaction_current_account_refusal"
    const val NAVIGATE_TO_SINGLE_SCRIPT_CONFIRMATION = "transaction-single-script-confirmation"
    const val NAVIGATE_TO_NUMERIC_OTP_SPV_SKP = "numeric-authorization-otp-spv-skp"
    const val NAVIGATE_TO_WAITING_TRANSITION = "waiting-transition"
    const val NAVIGATE_TO_ACCOUNT_MAINTENANCE_SUPERVISOR_OTP = "numeric-am-supervisor-otp"
    const val NAVIGATE_TO_NUMERIC_OTP_SPV_SWEEP_ACCOUNT = "numeric-authorization-otp-spv-sweep-account"
    const val NAVIGATE_TO_SELF_SERVICE_OVERBOOKING = "numeric-ss-otp-overbooking"
    const val NAVIGATE_TO_SELF_SERVICE_BI_FAST = "numeric-ss-otp-bifast"
    const val NAVIGATE_TO_SELF_SERVICE_RTGS = "numeric-ss-otp-rtgs"
    const val NAVIGATE_TO_CUSTOMER_INFORMATION_SELF_SERVICE = "customer-information-self-service"
    const val NAVIGATE_TO_CUSTOMER_INFORMATION_SPV_SELF_SERVICE = "customer-information-spv-self-service"
    const val NAVIGATE_TO_SELF_SERVICE_CUSTOMER_PIN = "transfer-self-service-pin-customer"
    const val NAVIGATE_TO_SELF_SERVICE_SPV_RTGS = "numeric-authorization-otp-spv-rtgs-self-service"
    const val NAVIGATE_TO_SELF_SERVICE_SPV_OVERBOOKING = "numeric-authorization-otp-spv-overbooking-self-service"
    const val NAVIGATE_TO_EDIT_TRANSACTION = "transaction-edit"
    const val NAVIGATE_TO_WARKAT_SIGNATURE = "transaction-warkat-signature-verification"
    const val NAVIGATE_TO_WAITING_CUSTOMER_SCREEN_STATUS = "waiting-customer-screen-status"
    const val NAVIGATE_TO_OTP_SPV_WITHDRAWAL = "numeric-authorization-otp-spv-cash-withdrawal"
    const val NAVIGATE_TO_REVIEW_OLD_BDS = "old-bds-review"
    const val NAVIGATE_TO_TRANSACTION_OVERVIEW_GB = "transaction-overview-gb"
    const val NAVIGATE_TO_TRANSACTION_OVERVIEW_CUSTOMER = "transaction-overview-customer"
    const val NAVIGATE_TO_TRANSACTION_RECEIPT = "transaction-receipt"
    const val NAVIGATE_TO_TRANSACTION_SUPERVISOR_CONFIRMATION = "transaction-supervisor-confirmation"
}

object ArgumentsDeepLink {
    const val KEY_ARG_OTP_SPV = "otpSpv"
    const val KEY_ARGS_SCENARIO = "scenario"
    const val KEY_ARGS_DATA = "argsData"
}